# -*- coding: utf-8 -*-
"""Assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_SN5QnE-YDzkZefnLn2HyrtOdqbAojN
"""

#try yourself

#give a try

#assignment1
#task3
session= "Fall"
year= 2022
print(session+"\n"+str(year)) # if u use \n to spreate line \n should be concatinated with strings always

print(session,year)
#method2

season = "Fall"
year = 2022
print(season, year, sep='\n')

#task4
name=input("Name please: ")
print("Your name is",name)

#task5
M=int(input())
N=int(input())
print("M^N"+":"+str(M**N))
#diff------------------------------------------------

#main method
M=int(input())
N=int(input())
print(str(M)+"^"+str(N)+":"+str(M**N))

#task6
corners=4
total_weight=int(input())
modulas=total_weight%corners #do mod
maximum_load=total_weight-modulas #do minus
print(maximum_load)

#method2
corners=4
total_weight=int(input())
floor=total_weight//corners #do floor
maximum_load=corners*floor #do into
print(maximum_load)

#task7
a=int(input())
b=int(input())
c=int(input())
d=float(input())
result= a**c+b*a-d/3
print(int(result))

#task8
chocolates=int(input())
num_fren=3
quotient=chocolates//num_fren
print("Each fren will receive",str(chocolates//num_fren)+"\n"+"the num of remain chocolates", str(chocolates-quotient*3))



#method2
chocolates=int(input())
num_fren=3
quotient=chocolates//num_fren
print("Each fren will receive",str(chocolates//num_fren))
print("the num of remain chocolates", str(chocolates-quotient*3))

#task9
M=input()
N=input()
print(str(N)+str(M))

#task10
line=input()
if line:
  first_cha=line[0]
  print(first_cha)
else:
  None

#task11
a=int(input())
if a%2==0:
  print(True)
else:
  print(False)