# -*- coding: utf-8 -*-
"""Assignment-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zYP9QVOeB5fPmrgbVupud8r2WV1zSoNO
"""

#task1
str1=input("enter a string:")

reversed_str=str1[::-1] #use slicing
print(reversed_str)

#task2
str1=input("enter a string: ")
point=int(input(""))

store=str1[point::-1]+str1[point+1::1]

print(store)

#task3
num=input("enter num: ")
new_num=""
flag=False

for i in num:
  if i=="0" or i=="1":
    new_num+=i
    flag=True
    continue

  else:
    print("Not a binary number")
    break
if flag==True:
  print("Binary Number")

#task4

string=input("enter your string: ")
cond=string[:-2:1]+"est"
if len(string)<4 and not string[-1:-3:-1]=="re":
  print(string)
elif len(string)>3 and not string[-1:-3:-1]=="re": # the issue was "re" not "er". look your string[] slicing clearly
  print(string+"er")
elif string[-1:-3:-1]=="re":
  print(cond)
elif string[-1:-4:-1]=="tse":
  print(string)
elif len(string)<4 and string[-1:-3:-1]=="re":
  print(cond)

#upper lower function for python

country="The UNITed StaTES Of America"
print(country.upper())
print(country.lower())

str1="       My     Name    is     Nabil       "
print(str1.lstrip())
print(str1.rstrip())
print(str1.strip())

#count function
str1= "BangladeshA"
temp=str1.count("a")
print(temp)

str1="Hello"
temp=str1.startswith("He")
print(temp)

#Returns the index of first occurrence of substring
str1='Bangladesh'
temp=str1.find("h")
print(temp)

#Replace every instance of oldstring with newstring
str1= "Nablia"
temp=str1.replace("a","la")
print(temp)

#how to make a copy of a list
list1=["Hersheys","Kitkat","Oreo", "MIMI", "Cadbury", "Monchuri-Milk Candy"]
Duplicate_list=list1[:]

print(Duplicate_list)

#The copied list remains unchanged when the item of original list gets modified:
original_list = ["Hersheys","Kitkat", "Oreo", "MIMI", "Cadbury", "Monchuri-Milk Candy"]
duplicate_list = original_list [:]
original_list[-1] = "Pran Mango Bar"
print(original_list)
print (duplicate_list)

##3) Looping through list using for loop:
family=['Mannan','Maksuda','Mahin','Sumia','Nabil']

for member in family:
  print(member)

#to check if an element is in a list
example_list = ["Hersheys","Kitkat","Oreo", "MIMI"]
if "MIMI" in example_list:
  print("Yes it is")

#to test if two variables refer to the same object.
x = ["apple", "banana", "cherry"]

y = ["apple", "banana", "cherry"]

print(x is y) #why false?

#5) To know the number of items in a list:
example_list = ["Hersheys","Kitkat",
"Oreo", "MIMI"]
print(len(example_list))



