# -*- coding: utf-8 -*-
"""cse110_assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N6sOJpG2nL-ocjRmgxGlKhco8YRvMhpx
"""

#task1
for i in range(24,-7,-6):
  if i==-6:
    print(i,end="")
  else:
    print(i,end=",")
print("\n")
for i in range(-10,21,5):
  if i==20:
    print(i,end="")
  else:
    print(i,end=",")
print("\n")
for i in range(18,64,9):
  if i==63:
    print(i,end="")
  else:
    print(i,end=",")
print("\n")


for i in range(18,64,9):
  if i==63:
    print("-"+str(i),end="")
  elif i%2==0:
    print(i,end=",")
  else:
    print(i,end=",")

#task2
car=input("car name: ")
time=int(input("give a number: "))
for i in range(1,time+1):
  print(car)

n = int(input())
count = n+1
count2 = 1
while count2 <= 10:
  print(count)
  count+=1
  count2+=1

car=input("car name: ")
times=int(input())
for i in range(1,times+1):
  print(car)

#task3
#task3
sum=0
for i in range(1,601):
  if i%7==0 and i%9==0:
    sum+=i
  else:
    pass
print(sum)

#while loop
sum=0
count=0
while count<=600:
  count+=1
  if count%7==0 and count%9==0:
    sum+=count
  else:
    pass
print(sum)

#task4
sum=0
for i in range(1,601):
  if (i%7==0 or i%9==0) and not (i%7==0 and i%9==0):
    sum+=i
  else:
    pass
print(sum)

#task5
for i in range(10,51):
  if i%2!=0:
    print(i,end=" ")

#task6
n=int(input("enter the ending number: "))
sum=0

for i in range(1,n+1):
  i=i**2
  sum+=i
print(sum)

#main task
n=int(input("enter last num: "))
pos=0
neg=0
sum=pos+neg
for i in range(1,n+1):
  if i%2==0: #check the even number
    i=i**2 #do power increment
    neg-=i #update neg with i decrement

  else:
    i=i**2
    pos+=i #update pos with i increment
  sum=pos+neg  # do addition of pos and neg under sum
print(sum)

#task7
count=0
sum=0

for i in range(1,11):
  n=int(input("enter numbers: "))
  if n%2!=0:
    sum+=n
    count+=1

  else:
    pass
avg=sum/count
print(f"The total of the odd numbers is {sum} and their average is {avg}")

#task8
n=int(input("enter a number: "))
sum=0
for i in range(1,n+1):
  if i%7==0:
    sum+=i
  else:
    pass
print(sum)

#task9
sum=0

for i in range(1,6):
  n=int(input("enter: "))
  sum+=n
  print(sum)

#task10

n=int(input("enter: "))
for i in range(n):
  if n!=0:
    rem1=n%10
    n=n//10

    if n==0:
      print(rem1,end="")
    else:
      print(rem1,end=",")

n= int(input())
for i in range(n):
  if n!=0:
    r=n%10
    n//=10
    if n==0:
      print(r,end="")
    else:
      print(r,end=",")

####
print(3//10)

#task10  # this loop runs 1234 times which is correct to do using loops only. but more sophisticated way is to use string
n=int(input("enter: "))

for i in range(n):
  if n!=0:
    rem=n%10
    n=n//10
    if n==0:
      print(rem,end="")
    else:
      print(rem,end=",")

#task11
#method1
n=input()

if n.isdigit():  #.isdigit() is used to check if the number is integer
  n_str=str(n)
  num_digits=len(n_str)
else:
  pass
print(num_digits)

#method2
n=int(input())

def print_alpha_nums(abc_list, num_list):
  for char in abc_list:
    for num in num_list:
      print(char, num)
  return
print_alpha_nums(['a','b','c'],[1,2,3])

print("i Said",("Nabil"*2),"two times")
print(True+False)
#you can multiply int with string

n=float(input())
n1=str(n)
print(len(n1))
print(n)

#count only numbers
n2=len(n1)-2 # 1 for decimal and 1 for 0
print(n2)

#task12
n=int(input("Enter:"))
n1=str(n)
n2=len(n1)
n3=10**(n2-1)
for i in range(n):
	if n//10==0:
	  print(n,end="")
    break
	else:
	  n4=n//n3
	  print(n4,end=",")
	  rem=n%n3
	  n3=int(n3/10)
	  n=rem

#task13
n=int(input("enter num: "))
num=1
divisor=1
print(1)
for i in range(n):
  num+=1
  if n%num==0:
    divisor+=1
    print(num)
  else:
    pass
print(f'Total divisor {divisor}')

#task13
n=int(input())
divisor=0

for i in range(1,n+1):  #here i starts from 1 not 0
  if n%i!=0:
    pass
  elif n%i==0:
    divisor+=1
    print(i)

  else:
    divisor+=1
    print(i)

print(f'Total divisor {divisor}')

#task14
n=int(input("enter: "))

sum_div=0
for i in range(1,n+1):

    if n%i==0:
      sum_div+=i

if sum_div==n:
  print(n,"is a perfect number.")
else:
  print(n,"is not a perfect number.")

#task14

n = int(input())
add=0
for i in range(1,n): #do not use n+1 here, cause it will use the last num of loop which is n=6
  if n%i==0:
    add+=i # by using n+1 there will be n=6 which will add 6 also
if add==n:
  print(n,"is a perfect number")
else:
  print(n,"is not a perfect number")

#task15
n=int(input())
divisor=0
for i in range(1,n+1):
  if n%i!=0:
    continue
  divisor+=1
if divisor==2:
  print(f'{n} is a prime number')
else:
  print(f'{n} is not a prime number')

#task16
n=int(input())
num=int(input())
sum=num
maximum=num
minimum=num
for i in range(n-1):
  num=int(input())
  if num>maximum:
    maximum=num
  elif num<minimum:
    minimum=num
  sum+=num
print("Maximum ",maximum)
print("Minimum ",minimum)
print("Average is",sum/n)

# Get the value of N from the user
N = int(input("Enter the value of N: "))

# Iterate through rows
for i in range(N):
    # Iterate through columns
    for j in range(N):
        # Print '+' without a newline
        print("+", end="") # for creating + square box you need to print + inside the nested loop.
    # Move to the next line after printing each row #print(): This line of code is used to insert a newline character, effectively moving the cursor to the next line. It's used after each row of '+' characters has been printed to ensure that the next row is printed on a new line.
    print()

#task17  / square printing
n=int(input())

for col in range(n):

  for row in range(n):
    print("+",end="")
  print()

#task18
row_num=int(input())
col_num=int(input())

for col in range(col_num):
  for row in range(1,row_num+1):
    print(row,end="")
  print()

#task19
rows = int(input())
for i in range(1, rows + 1):
  for j in range(1, i + 1):1
    print(j, end=' ')
  print('')